packages:
  - 'core'
  - 'cli'
  - 'helpers-android'
  - 'helpers-anthropic'
  - 'helpers-demo'
  - 'helpers-deepl'
  - 'helpers-googlecloud'
  - 'helpers-html'
  - 'helpers-ios'
  - 'helpers-java'
  - 'helpers-json'
  - 'helpers-openai'
  - 'helpers-po'
  - 'helpers-translated'
  - 'helpers-xliff'
  - 'server'
  - 'helpers-lqaboss'