// Auto-generated by scripts/publish-workspaces.js - DO NOT EDIT
export const l10nMonsterPackage = "@l10nmonster/core";
export const l10nMonsterVersion = "3.1.1";
export const l10nMonsterDescription = "L10n Monster Core Module";
